#!/bin/bash

set -euo pipefail

if [ "$1" = "execute" ]
then
    export RUST_BACKTRACE=1
    cat "$2" | ~/Projects/ni-run/tasks/2-bc-interpreter/target/debug/interpreter
else
    echo "Unknown command: $1. Supported commands: execute"
    exit 1
fi
