#!/bin/bash
if [ "$1" = "run" ]
then
    $PARSER parse "$2" --format=json | ~/Projects/ni-run/tasks/1-ast-interpreter/target/release/interpreter
else
    echo "Unknown command: $1. Supported commands: run"
    exit 1
fi
