#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

export RUST_BACKTRACE=1
if [ "$1" = "execute" ]
then
    "$SCRIPT_DIR/target/release/interpreter" < "$2"
elif [ "$1" = "parse" ]
then
    $PARSER parse "$2" --format=json
elif [ "$1" = "compile" ]
then
    "$SCRIPT_DIR/target/release/compiler" < "$2"
else
    echo "Unknown command: $1. Supported commands: parse, compile, execute"
    exit 1
fi
